### ISSUE TITLE
Recipes for Al, F, P are not displaying

### ISSUE THREAD

**Issue by prckent** [QMCPACK/pseudopotentiallibrary#22]
Likely typos in the php or inconsistencies in how elements are named.

(Observed after #21 )

**Comment by mcbennet** [comment]
For F, index.php needs the following correction: "flourine" -> "fluorine"

Similar for Al and P, however, the correct spellings in index.php were already included in my commits but these changes are not propagating to the server which is hosting the website.

**Comment by mcbennet** [comment]
The change to F in index.php has been committed and a PR generated.

Once merged, to have the changes show up on the website I assume some sort of pull or clone to the host's server will be required.

**Comment by prckent** [comment]
Fixed by @sanluyene
