### ISSUE TITLE
Add 1/r "pseudopotential" to H

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/pseudopotentiallibrary#33]
Can we include a bare coulomb "pseudopotential" in H?  Other than being good for hydrogen DFT stuff, it's nice to have it around for debugging purposes.  Not a standard use case, but I think it would be useful.

**Comment by prckent** [comment]
Yes. This is a good idea. Presumably you have some canonical files? A QMCPACK .xml and a UPF for QE?

**Comment by rcclay** [comment]
As a matter of fact, I do...  somewhere.  I'll find them and create a PR dropping these into the repository within the next few days.
