### ISSUE TITLE
F ccECP missing

### ISSUE THREAD

**Issue by dubeckym** [QMCPACK/pseudopotentiallibrary#47]
hi, F ccECP is declared in available ECPs but it's not present for download
thanks, m.

**Comment by prckent** [comment]
@camelto2 Is there an F ccECP yet or are there only the two Trail-Needs potentials?

**Comment by camelto2** [comment]
There is not currently one, only the Trail-Needs potentials. A new paper will be submitted soon adding up through Kr, and that will fill in our missing potentials. It should be online fairly soon, in the next few weeks. I think we will upload them with the arxiv submission.

**Comment by prckent** [comment]
Thanks for these developments.

**Comment by dubeckym** [comment]
thanks a lot! looking fw, m
