### ISSUE TITLE
DOES ANYONE HAVE THE  PSEUDO POTENTIAL IODINE martin troullier PBE ?

### ISSUE THREAD

**Issue by yagolopes2302** [QMCPACK/pseudopotentiallibrary#94]
DOES ANYONE HAVE THE  PSEUDO POTENTIAL IODINE martin troullier PBE for CPMD  ?

**Comment by prckent** [comment]
This question is probably best addressed on a CPMD mailing list or support forum -- the library here is for quantum chemistry and other many body techniques such as Quantum Monte Carlo, not density functional methods and codes. I was able to find several sources of Troullier Martins files, some LDA and some PBE. See e.g. https://www.abinit.org/sites/default/files/PrevAtomicData/psp-links/gga_fhi.html  and https://www.abinit.org/norm-conserving-pseudopotentials . You would likely need to adapt the format or regenerate them. Good luck.
