### ISSUE TITLE
Proper reference for core-valence polarized ccECP-pCVQZ basis set for Iron?

### ISSUE THREAD

**Issue by vvp-nsk** [QMCPACK/pseudopotentiallibrary#95]
Hi!

Could you please specify what article must be cited for the basis set available at:

https://pseudopotentiallibrary.org/recipes/Fe/ccECP/Fe.cc-pCVQZ.gaussian

?

Thank you in advance!

With best regards, 
Victor

**Comment by prckent** [comment]
It is from https://doi.org/10.1063/1.5040472 which also has the ccECP Fe potential.

**Comment by vvp-nsk** [comment]
Many thanks for the prompt reply!
