### ISSUE TITLE
Supporting the psml format?

### ISSUE THREAD

**Issue by zerothi** [QMCPACK/pseudopotentiallibrary#97]
Hi,

Will the pseudopotentials here be able to support the psml formats? Or is there any limitation in this?

Links: https://siesta-project.github.io/psml-docs/
https://doi.org/10.1016/j.cpc.2018.02.011
And arXiv: https://arxiv.org/abs/1707.08938

Thanks!

**Comment by prckent** [comment]
Good question. The pseudopotentials are initially produced in the semi-local format, which is sufficient for real-space QMC and for Quantum Chemical methods. These formats are long established. Projectors added for codes needing them, typically plane wave codes such as Quantum ESPRESSO but also codes such as RMG-DFT. Therefore it should be possible to write a converter to any code or format that takes norm conserving potentials. If a format is popular enough we could include conversions on the website.

**Comment by zerothi** [comment]
Ok, thanks for your feedback.

**Comment by prckent** [comment]
Let us know if you need any help with a conversion. We think it would should be straightforward. I'll close this but we can reopen if needed.
